// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gchat/internal/biz"
	"gchat/internal/conf"
	"gchat/internal/data"
	"gchat/internal/server"
	"gchat/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	v := biz.NewJwtGenerator(auth)
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(v, userRepo, logger)
	chatRepo := data.NewChatRepo(dataData, logger)
	chatUsecase := biz.NewChatUsecase(chatRepo, logger)
	messageRepo := data.NewMessageRepo(dataData, logger)
	messageUsecase := biz.NewMessageUsecase(messageRepo, logger)
	gchatService := service.NewGchatService(userUsecase, chatUsecase, messageUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, auth, gchatService, logger)
	grpcServer := server.NewGRPCServer(confServer, gchatService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
